services:
  be:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  celery:
    build: .
    command: celery
    depends_on:
      - db
      - redis
    env_file:
      - .env
volumes:
  postgres_data:
  redis_data:
