services:
  be:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
volumes:
  postgres_data:
