# Generated by Django 5.2.3 on 2025-06-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("skills", models.JSONField(help_text="List of skills")),
                ("projects", models.JSONField(help_text="List of projects")),
                ("bio", models.TextField()),
                (
                    "contacts",
                    models.JSONField(
                        help_text="Contact information (email, phone, etc.)"
                    ),
                ),
            ],
        ),
    ]
