# Generated by Django 5.2.3 on 2025-06-21 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=255)),
                ("query_string", models.TextField(blank=True)),
                ("remote_ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
